
Current version and information on where to obtain
Cabletron Private Enterprise MIBs is available via the web at:

     http://www.cabletron.com/pub/snmp/mibs/enterprise/mib-versions.html

or go directly to the FTP site at:

     ftp://ftp.cabletron.com/pub/snmp/mibs/enterprise

Cabletron Systems
2/98

**Disclaimer: The Internet Assigned Numbers Authority (IANA) warns
that there is no assurance that the file pointed to has passed the
mib-checker.**