
================================================================

The Shiva Enterprise MIB is available via anonymous ftp from host
Shiva.COM. The latest document will always be available from that
location.

Shiva Corporation
3/93
================================================================

**Disclaimer: The Internet Assigned Numbers Authority (IANA) warns
that there is no assurance that the file pointed to has passed the
mib-checker.**

